README.org
kodata/features/verify-conformance-release.feature
pkg/suite/suite.go

Add allowance for a single commit

---

hack/generate-conformanceyaml.sh

Adds a separate callable script for generating conformance yaml

Add generate-conformanceyaml.sh

---

pkg/suite/suite.go

Ensure that e2e.log k8s version matches folder structure

---

go.mod
go.sum
pkg/suite/suite.go

Use new sonobuoy junit structure for new versions

---

pkg/plugin/plugin.go
pkg/suite/suite.go

Fixes: https://github.com/cncf-infra/verify-conformance/issues/16

Add PR status updates

---

README.org
verify-conformance-release-deployment-dev-temp.yaml

Switches to using `ko apply` for bringing up development version

Use ko apply

---

cmd/trial-implementation/main.go
kodata/features/verify-conformance-release.feature
pkg/suite/suite.go

The field _contact_email_address_ is to be introduced as a requirement for PRODUCT.yaml in submissions.

Add contact_email_address validation for PRODUCT.yaml

---

.github/workflows/build.yml

reintroduces the assume role for deployment

Assume role for deploy

---

pkg/plugin/plugin.go

Add comment to show bot auto deploy

---

.github/workflows/update-conformance-yaml.yml

Regex is wrong and not resulting in output in
https://github.com/cncf-infra/verify-conformance/actions/runs/3670222834/jobs/6204610586

Update checking of changes

---

cmd/trial-implementation/main.go
go.mod
kodata/features/verify-conformance-release.feature
pkg/suite/suite.go

Support junit test info for v1.25 and above

---

.github/workflows/build.yml

related: https://github.com/cncf-infra/verify-conformance/pull/50

Add missing release condition to image sign

---

.github/workflows/reusable-update-go-version.yml
.github/workflows/update-go-version.yml

automatically updates the Go version to the latest stable version in go.mod

Add Go version auto update

---

.github/workflows/release.yml

Add missing cosign to release

---

.github/workflows/release.yml

ensure contents can be written to

Update release permissions

---

.github/workflows/code-quality-check.yml
.github/workflows/reusable-go-test.yml
.github/workflows/reusable-go-vet.yml
.github/workflows/reusable-gofmt.yml
.github/workflows/reusable-golangci-lint.yml

test, lint, format and vet to code

Add code quality checks

---

.github/workflows/code-quality-check.yml

actions must have the version when being included

Add missing versions to actions

---

.github/workflows/reusable-golangci-lint.yml

failing due to timeout on https://github.com/cncf-infra/verify-conformance/actions/runs/4891892570/jobs/8732963181?pr=65#step:6:28

Add timeout to go linter

---

.github/workflows/reusable-go-test.yml
pkg/plugin/plugin_test.go

related: https://github.com/cncf/apisnoop/issues/745

Add test in plugin.go for GetStableVersion

---

.github/workflows/reusable-gofmt.yml

gofmt reports no failure, results only show up in output

Add fail to gofmt

---

docs/resources.md

related: https://github.com/cncf-infra/verify-conformance/issues/78

Add resources document

---

.github/workflows/update-conformance-yaml.yml
.github/workflows/update-stable-txt.yml
hack/generate-conformanceyaml.sh

- run on each hour
- remove unfulfillable condition from conformanceyaml
- fix variable evaluation for stable-txt

fix: conformance and stable automation bugs

---

.github/workflows/update-conformance-yaml.yml

ensure it noticies files changed when there are changes

chore: update conformanceyaml git files changed

---

.github/workflows/update-conformance-yaml.yml

fix: remove random fi

---

kodata/features/verify-conformance-release.feature
pkg/suite/suite.go
pkg/suite/suite_test.go

prevent any commits of unexpected files
fixes: #98

feat: add requirement for only required files in submission

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/reusable-go-test.yml
.github/workflows/reusable-go-vet.yml
.github/workflows/reusable-gofmt.yml
.github/workflows/reusable-golangci-lint.yml
.github/workflows/reusable-update-go-version.yml
.github/workflows/update-conformance-yaml.yml
.github/workflows/update-stable-txt.yml

update the imports for the workflows

chore: update workflow imports

---

kodata/features/verify-conformance-release.feature

ensure it matches up with what's expected

fix: feature syntax for required file for regex

---

.github/workflows/reusable-update-go-version.yml
.github/workflows/update-conformance-yaml.yml
.github/workflows/update-stable-txt.yml
.gitignore
hack/test.sh

- add .gitignore
- add handy hack/test.sh to run unit tests and output coverage html
- use force push for existing branch on update conformance.yaml
- use commit timestamp in update-go-version

chore: misc changes

---

.github/workflows/update-stable-txt.yml

chore: run update-stable-txt more frequently

---

pkg/plugin/plugin.go
pkg/plugin/plugin_test.go

Intends to check whether release is available before running the PRSuite and return a message, status and set of labels if not.
related: #47

Update flow of release being available

---

CONTRIBUTING.md
LICENSE
OWNERS
SECURITY.md
SECURITY_CONTACTS
code-of-conduct.md

sync up with Kubernetes project standards

chore: add Kubernetes project template files

---

pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/suite/suite.go

adds more tests for plugin functions
coverage now at 79.7%

chore: increase unit test coverage in plugin

---

pkg/plugin/plugin.go

- pr title must be include "conformance results for" to run suite
- to get version unavailable please wait message, the conformance yaml must have os.isnotexist error type

chore: update version available and conformance pr

---

.gitignore
.ko.yaml
cloudbuild.yaml
docs/building.md

- build on Google cloudbuild
- add building docs

feat: add Google cloudbuild config

---

.github/workflows/reusable-golangci-lint.yml

chore: use golangci-lint v1.55.2 in ci

---

kodata/features/verify-conformance-release.feature
pkg/plugin/plugin.go
pkg/plugin/plugin_test.go
pkg/suite/suite.go

to resolve some flakey behaviour

chore: remove product_logo_url content type check

---

README.org
docs/README.org
docs/ci.org

chore: add CI docs

---

docs/development.org
hack/local-dev/ghproxy.yaml
hack/local-dev/kind-config.yaml
hack/local-dev/kustomization.yaml
hack/local-dev/local-registry-hosting.yaml
hack/local-dev/start-kind.sh

remove requirement for access to ghcr.io/cncf-infra/verify-conformance

chore: update dev docs to use local registry

---

.github/workflows/update-conformance-yaml.yml

removed conformance.yaml files weren't being included

fix: inclusion of deleted conformance yaml

---

.github/workflows/publish.yml

chore: add missing dependencies to publish

---

.github/workflows/code-quality-check.yml
.github/workflows/publish.yml

chore: code quality check push run-on

---

config/default/kustomization.yaml
config/verify-conformance/configmap.yaml
config/verify-conformance/deployment.yaml
hack/generate-conformanceyaml.sh
hack/local-dev/kustomization.yaml
hack/local-dev/start-kind.sh
hack/publish-in-container.sh
hack/publish.sh
hack/update-all-actions-imports.sh
hack/update-stable-txt.sh
hack/verify-all.sh
hack/verify-gobuild.sh
hack/verify-gofmt.sh
hack/verify-goimports.sh
hack/verify-golangci-lint.sh
hack/verify-golint.sh
hack/verify-gotest.sh
hack/verify-govet.sh
hack/verify-govulncheck.sh
hack/verify-spellcheck.sh
internal/common/common.go
internal/common/common_test.go
internal/plugin/plugin.go
internal/plugin/plugin_test.go
internal/suite/suite.go
internal/suite/suite_test.go
internal/types/types.go
main.go

adds Kubernetes copyright headers for Apache 2.0

chore: add Kubernetes copyright headers

---

README.md
docs/README.md
docs/about.md
docs/development.md
docs/maintainance.md

describe function and purpose of program internals

chore: add about doc

---

docs/maintainance.md

chore: update maintainance doc workflow & gh app

---

main.go

when specified, read from a file and handle pull-request event then exit

feat: add handling of pull-request events

---

internal/plugin/plugin.go
internal/plugin/plugin_test.go
internal/suite/suite.go

make sure that there's a clear message when the version is too old to be approved
fixes: #179

chore: ensure there's an outta date message

---

main.go

don't fail on no pr event file found when no file specified

fix: separate handling of pr event

---

OWNERS

I am unable to meaningfully contribute to reviews or approvals for this project, and so am removing myself as an approver.

Remove Zach from OWNERS file

---

OWNERS
SECURITY_CONTACTS

Adding:
- Koray Oksay
- Mario Fahlandt
- Marko Mudrinić

Add Kubermatic to OWNERS and SECURITY_CONTACTS
